### ISSUE TITLE
Show: Papers covering UBJSON

### ISSUE THREAD

**Issue by jviotti** [thebuzzmedia/universal-binary-json#115]
Hey there!

As part of my MSc dissertation at University of Oxford, I wrote and published two papers covering the characteristics of various binary serialization formats, including UBJSON and performing a space-efficiency benchmark, respectively.

Sharing them here in case anybody finds them interesting! The first paper explains how UBJSON works including an annotated hexadecimal example and the second compares UBJSON to various other popular serialization formats.

- A Survey of JSON-compatible Binary Serialization Specifications: https://arxiv.org/abs/2201.02089
- A Benchmark of JSON-compatible Binary Serialization Specifications: https://arxiv.org/abs/2201.03051

All the best!

**Comment by ppKrauss** [comment]
Hi @jviotti , do you have some modern comparison adding **JSONb**, of the PostgreSQL's implementation?  

----

Some references:

* https://www.postgresql.org/docs/current/functions-json.html
* https://www.postgresql.org/docs/current/datatype-json.html

Benchmarks:
* https://www.enterprisedb.com/news/new-benchmarks-show-postgres-dominating-mongodb-varied-workloads
* https://www.enterprisedb.com/blog/comparison-mongodb-vs-postgresql

**Comment by jviotti** [comment]
@ppKrauss I don't, but I'd be interested in measuring this. I'm maintaining a reproducible and open-source binary JSON benchmark over here: https://sourcemeta.github.io/json-size-benchmark/ (the code is in https://github.com/sourcemeta/json-size-benchmark).

Do you know if JSONb can be used independently outside PostgreSQL (i.e. as a C library or something like that)?

**Comment by ppKrauss** [comment]
> Do you know if JSONb can be used independently outside PostgreSQL (i.e. as a C library or something like that)?

Hi @jviotti , you can see the source code at https://github.com/postgres/postgres and use email discussion channel  to check if JSONb exists in a standalone library... I am supposing that not exists, but communit can help you to build one.

The ideal benchmark is running SQL queries, that are noSQL when you use the "JSONb algebra" or the "[JSON Path Language](https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-SQLJSON-PATH)". 

PS: for benchmark scripts you can use [`pgbench`](https://www.postgresql.org/docs/current/pgbench.html) ([comments](https://severalnines.com/blog/benchmarking-postgresql-performance)) and TAP, see  [pgTap](https://pgtap.org/) or internal ([regress-tap](https://www.postgresql.org/docs/current/regress-tap.html) as [commented](https://www.2ndquadrant.com/en/blog/using-postgresql-tap-framework-extensions/)).

**Comment by jviotti** [comment]
Closing this issue. It has been opened for a while and served its purpose. Probably no need to have it open forever :) Thanks a lot!
