### ISSUE TITLE
Rules for handling unsigned values

### ISSUE THREAD

**Issue by to-miz** [thebuzzmedia/universal-binary-json#119]
The specification doesn't specify how unsigned values should be serialized. For instance lets say I have an unsigned 16bit short value 0xFFFF, does this have to be serialized as `[I][-1]` or `[l][65535]`?
This matters because it also dictates how lengths for strings and containers are stored. If unsigned values can be stored as negative values, then integer conversion/promotion rules need to be added to the specifiaction. Otherwise there should still be a mention on how to handle unsigned values. See also #118 which is a consequence of this.

Another missing specification is the integer storage format for signed integers. I assume it is 2s complement, but it is missing from the specification.

**Comment by shelacek** [comment]
Although it is not explicitly specified, I think it is clear from the context and common practice.

The spec states:

> It is always recommended to use the smallest numeric type that fits your needs.

And in the "_Signage & Min/Max Values_" there are UBJSON numeric types with ranges.

The value `0xFFFF` in `uint16_t` is 65535, so the smallest numeric type that can handle this number is `int32`. The same value in `int16_t` is -1 and can be stored in `int8`. It depends on the numeric value itself, not on the input type.

But you're right - the specs could be better.

**Comment by to-miz** [comment]
>It depends on the numeric value itself, not on the input type.

Thanks I was not clear on this but upon reviewing the spec it makes more sense. I think the absence of some unsigned types led me to believe that we were supposed to use type casts. But this is more sensible. I will close this issue since the misunderstanding was on my part.
