### ISSUE TITLE
UBJSON Crash-safe?

### ISSUE THREAD

**Issue by HHOPs** [thebuzzmedia/universal-binary-json#120]
We are looking for a "Crash-safe" data storage format for safe aquisition and temporal storage of flight test data (in-flight). Is UBJSON crash-safe during operations (software crash, power outage, ...)? Is there toolchains for efficient data access available (Matlab, Python, ...)? Thanks and best regards!

**Comment by rkalla** [comment]
The format is agnostic to the problem - but structurally it will have the
same requirements as JSON and will depend on the operation of the toolchain
you are using to WRITE and READ the UBJSON.

UBJSON is streaming-friendly, so in a hypothetical crash situation that you
only wrote out a portion of the intended payload, you would be able to
successfully parse UP TO the point of failure just fine.

So if you wrote 11 records and the 11th one was corrupted half way through,
you could read the 10 prior ones without issue, hit the 11th and encounter
the corrupted structure and then just discard it.

This will depend on the library you use but any of the more modern or
maintained UBJSON libraries should handle this case just fine.

**Comment by AnyCPU** [comment]
UBJSON is safe as much as possible, all the other concerns are up to a library you want to use, architecture and your data flow.
