### ISSUE TITLE
Lua UBJSON library

### ISSUE THREAD

**Issue by fperrad** [thebuzzmedia/universal-binary-json#121]
I wrote <https://framagit.org/fperrad/lua-ubjson>.
You could add it to the list in <https://ubjson.org/libraries/>

**Comment by rkalla** [comment]
Added!

**Comment by fperrad** [comment]
It is Lua, not LUA.
See <https://www.lua.org/about.html>

**Comment by rkalla** [comment]
A pox upon me! (fixed :) )
