### ISSUE TITLE
Restrict the Char type value to 0-127 range

### ISSUE THREAD

**Issue by dmitry-ra** [thebuzzmedia/universal-binary-json#56]
It would be nice to remove the note 
```
It is beyond the scope of the Universal Binary JSON Specification to define semantics of char
values in the remaining decimal range of 128-255. Implementors that wish to utilize values of
the char type in this range must be aware that these values are incompatible with other standard
UBJSON encoder/decoder implementations.

If a closed system is being defined and a high value is placed on being able to define additional
semantics around the 128-255 values of char and compatibility with other external, standard 
UBJSON implementations is not needed, then implementors should feel free to utilize this range of 
undefined values.

```
Setting explicit restrictions to the range of Char value ​​will make more consistent specification and will promote more clean implementations.

Rule is simple: if string value after UTF-8 encoder has a size 1 byte, then it can be encode as Char type. In other case - this is string [S].

UTF-8 itself does not allow values more than 127 in single byte - setting high bit to "1" is a signal to switch to next byte.

**Comment by thebuzzmedia** [comment]
Resolving

* Re-updated the title to match @dmitry-ra original intent.
* Reading back through this thread and considering some viewpoints I feel [C] should stay for no other reason than syntactic surgar (i.e. more enhanced tooling support).
* Restriction clarified in the spec - http://ubjson.org/type-reference/value-types/#char

**Comment by Miosss** [comment]
@thebuzzmedia 
So you changed your decision now and [C] stays, yes?

**Comment by thebuzzmedia** [comment]
@Miosss Yes - [C] stays, but is more strictly defined as a single UTF-8 char (decimal values 0-127).
