### ISSUE TITLE
Support array/object length in bytes

### ISSUE THREAD

**Issue by mwijngaard** [thebuzzmedia/universal-binary-json#67]
I've read through most of the quite extensive discussions on the counts for objects and arrays (and whether they should be in bytes or not) and can understand that most parser writers will have a preference for using the counts to pre-size datastructures. Having the size of an object or array in bytes, however, can be extremely useful when trying to parse only a subset of the data (ie running an xpath-like query without streaming the whole document). Having the size in bytes can make it very easy to skip over a nested document or array while parsing. This was one of the features that caught my eye in the BSON spec at first. I can't really find a good reason for not including it here, apart from that it's not useful for presizing datastructures (which is correct of course). Are there some posts I overlooked?

**Comment by thebuzzmedia** [comment]
@mwijngaard it's a good call out and something we discussed quite a bit a few years back.

Where we landed is that in REALLY performance sensitive cases where you are likely transferring binary payloads, your array count size would likely represent the byte size you are looking for (e.g. "4500 32-bit floats") and can easily be skipped over.

For the greater case, i.e. supporting byte size on ALL containers, required much too much load/state for the generator to keep track of and was allowed less of a 'streaming' approach to generation as recursive container sizes would need to be considered (more state pushed to generator side).

Making the size optional also lead to the pain of the generator AND parser needing to support all these different combinations... not insurmountable, just started to realize that a lot of complexity was creeping into the spec.

CLOSING (for these reasons) - if you disagree or want to discuss further it's no problem, feel free to re-open.
